/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_andreflores;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Popup;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author andre
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppM_tree = new javax.swing.JPopupMenu();
        MI_loadfile = new javax.swing.JMenuItem();
        MI_refresh = new javax.swing.JMenuItem();
        ppmenu_tabla = new javax.swing.JPopupMenu();
        clearTable = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        tf_Command = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MI_newfile = new javax.swing.JMenuItem();
        MI_importfile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MI_ClearCommandLine = new javax.swing.JMenuItem();
        MI_cleartable = new javax.swing.JMenuItem();
        MI_RefreshTrees = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        MI_loadfile.setText("Load File");
        MI_loadfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MI_loadfileMouseClicked(evt);
            }
        });
        MI_loadfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_loadfileActionPerformed(evt);
            }
        });
        ppM_tree.add(MI_loadfile);

        MI_refresh.setText("Refresh trees");
        MI_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_refreshActionPerformed(evt);
            }
        });
        ppM_tree.add(MI_refresh);

        clearTable.setText("jMenuItem10");
        clearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTableActionPerformed(evt);
            }
        });
        ppmenu_tabla.add(clearTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Enter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "name", "category", "price", "aisle", "bin"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("CSVs");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf_Command, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Command, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        MI_newfile.setText("New File");
        MI_newfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_newfileActionPerformed(evt);
            }
        });
        jMenu1.add(MI_newfile);

        MI_importfile.setText("Import File");
        MI_importfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_importfileActionPerformed(evt);
            }
        });
        jMenu1.add(MI_importfile);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Window");

        MI_ClearCommandLine.setText("Clear Command Line");
        MI_ClearCommandLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ClearCommandLineActionPerformed(evt);
            }
        });
        jMenu2.add(MI_ClearCommandLine);

        MI_cleartable.setText("Clear Table");
        MI_cleartable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_cleartableActionPerformed(evt);
            }
        });
        jMenu2.add(MI_cleartable);

        MI_RefreshTrees.setText("Refresh Trees");
        jMenu2.add(MI_RefreshTrees);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem6.setText("Product Structure ");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Commands");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void MI_newfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_newfileActionPerformed

        String nombreArchivo = JOptionPane.showInputDialog("ingrese el nombre del archivo:");
        DefaultTreeModel modeloArbol = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode padre = (DefaultMutableTreeNode) modeloArbol.getRoot();
        DefaultMutableTreeNode hijo = new DefaultMutableTreeNode(nombreArchivo);
        padre.add(hijo);
        modeloArbol.reload();
    }//GEN-LAST:event_MI_newfileActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked

        if (evt.getButton() == 3) {
            if (evt.isMetaDown()) {
                int row = jTree1.getClosestRowForLocation(
                        evt.getX(), evt.getY());
                jTree1.setSelectionRow(row);
                v1 = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
                ppM_tree.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1MouseClicked

    private void MI_loadfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MI_loadfileMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_MI_loadfileMouseClicked

    private void MI_loadfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_loadfileActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
        int rows = 0;

        String id = "";
        String name = "";
        String category = "";
        String price = "";
        String aisle = "";
        String bin = "";
        ArrayList<Producto> productos = new ArrayList();

        File archivo = new File((String) v1.getUserObject());
        while (jTable1.getValueAt(rows, 0) != null) {
            for (int i = 0; i <= 6; i++) {
                if (i == 0) {
                    id = (String) jTable1.getValueAt(rows, i);
                } else if (i == 1) {
                    name = (String) jTable1.getValueAt(rows, i);

                } else if (i == 2) {
                    category = (String) jTable1.getValueAt(rows, i);

                } else if (i == 3) {
                    price = (String) jTable1.getValueAt(rows, i);

                } else if (i == 4) {
                    aisle = (String) jTable1.getValueAt(rows, i);

                } else if (i == 5) {
                    bin = (String) jTable1.getValueAt(rows, i);

                }

            }
            productos.add(new Producto(id, name, category, price, aisle, bin));
            rows++;

        }
        String salida = "";
        System.out.println(productos.size());
        for (int i = 0; i < productos.size(); i++) {
            salida += productos.get(i).getId() + "," + productos.get(i).getName() + "," + productos.get(i).getCategory() + "," + productos.get(i).getPrice() + "," + productos.get(i).getAisle() + "," + productos.get(i).getBin() + "\n";

        }
        try {
            FileWriter fw = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(salida);
            bw.flush();
            bw.close();
            fw.close();
        } catch (Exception e) {
            e.printStackTrace();

        }

// TODO add your handling code here:
    }//GEN-LAST:event_MI_loadfileActionPerformed

    private void MI_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_refreshActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_MI_refreshActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String texto = tf_Command.getText();
        String[] arr = texto.split(" ");
        if (arr[0] == "./load") {
            File archivo = new File(arr[1]);
            DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
            int rows = 0;

            String id = "";
            String name = "";
            String category = "";
            String price = "";
            String aisle = "";
            String bin = "";
            ArrayList<Producto> productos = new ArrayList();

            while (jTable1.getValueAt(rows, 0) != null) {
                for (int i = 0; i <= 6; i++) {
                    if (i == 0) {
                        id = (String) jTable1.getValueAt(rows, i);
                    } else if (i == 1) {
                        name = (String) jTable1.getValueAt(rows, i);

                    } else if (i == 2) {
                        category = (String) jTable1.getValueAt(rows, i);

                    } else if (i == 3) {
                        price = (String) jTable1.getValueAt(rows, i);

                    } else if (i == 4) {
                        aisle = (String) jTable1.getValueAt(rows, i);

                    } else if (i == 5) {
                        bin = (String) jTable1.getValueAt(rows, i);

                    }

                }
                productos.add(new Producto(id, name, category, price, aisle, bin));
                rows++;

            }
            String salida = "";
            System.out.println(productos.size());
            for (int i = 0; i < productos.size(); i++) {
                salida += productos.get(i).getId() + "," + productos.get(i).getName() + "," + productos.get(i).getCategory() + "," + productos.get(i).getPrice() + "," + productos.get(i).getAisle() + "," + productos.get(i).getBin() + "\n";

            }
            try {
                FileWriter fw = new FileWriter(archivo);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(salida);
                bw.flush();
                bw.close();
                fw.close();
            } catch (Exception e) {
                e.printStackTrace();

            }
        } else if (arr[0].equalsIgnoreCase("./create") && arr[2].equalsIgnoreCase("-single")) {
            System.out.println("h");
            DefaultTreeModel modeloArbol = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode padre = (DefaultMutableTreeNode) modeloArbol.getRoot();
            DefaultMutableTreeNode hijo = new DefaultMutableTreeNode(arr[1]);
            padre.add(hijo);
            modeloArbol.reload();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getButton() == 3) {
            if (evt.isMetaDown()) {
                ppmenu_tabla.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void clearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTableActionPerformed
        int rows = 0;
        while (jTable1.getValueAt(rows, 0) != null) {
            for (int i = 0; i < 6; i++) {
                jTable1.setValueAt("", rows, i);
            }
            rows++;
        }
    }//GEN-LAST:event_clearTableActionPerformed

    private void MI_cleartableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_cleartableActionPerformed
        int rows = 0;
        while (jTable1.getValueAt(rows, 0) != null) {
            for (int i = 0; i < 6; i++) {
                jTable1.setValueAt("", rows, i);
            }
            rows++;
        }
    }//GEN-LAST:event_MI_cleartableActionPerformed

    private void MI_ClearCommandLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ClearCommandLineActionPerformed

        tf_Command.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_MI_ClearCommandLineActionPerformed

    private void MI_importfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_importfileActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_MI_importfileActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        JOptionPane.showMessageDialog(this, "Comandos: \n"
                + "1. ./create (nombre archivo).txt -single: crea el archivo. \n"
                + "2. ./load (nombre archivo).txt: carga la tabla al archivo. \n"
                + "3. ./clear: vacia la tabla. \n"
                + "4. ./refresh: refresca el arbol y agrega los nuevos archivos.");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    DefaultMutableTreeNode v1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MI_ClearCommandLine;
    private javax.swing.JMenuItem MI_RefreshTrees;
    private javax.swing.JMenuItem MI_cleartable;
    private javax.swing.JMenuItem MI_importfile;
    private javax.swing.JMenuItem MI_loadfile;
    private javax.swing.JMenuItem MI_newfile;
    private javax.swing.JMenuItem MI_refresh;
    private javax.swing.JMenuItem clearTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPopupMenu ppM_tree;
    private javax.swing.JPopupMenu ppmenu_tabla;
    private javax.swing.JTextField tf_Command;
    // End of variables declaration//GEN-END:variables

}
